### ISSUE TITLE
Audio requires click to start on Safari for iOS

### ISSUE THREAD

**Issue by kamblack** [KamboBlack/AudioFade#2]
Gotta find a way to have the audio begin playing when it should automatically on Safari iOS as it currently does on other browsers.

**Comment by ghost** [comment]
I don't see that it works on mobile devices in the first place, alas. Otherwise a great script!

**Comment by kamblack** [comment]
Closed - Testing shows that it works on most mobile browsers. If it still requires a tap on iOS Safari to start, this should be seen as a design consideration - that the user should acknowledge their presence on the site before autoplaying any media as a consideration of the user's potential connection issues.
