### ISSUE TITLE
Don't start audio until position is scrolled to

### ISSUE THREAD

**Issue by keithpickering** [KamboBlack/AudioFade#3]
Hi, great plugin!

Currently it seems to start playing all the audio files on page load, but with the volume down. Is there a way for me to keep from starting each audio instance until the "start" position is first scrolled to?

**Comment by kamblack** [comment]
It should work if you comment out [line 23](https://github.com/KamboBlack/AudioFade/blob/master/js/AudioFade.js#L23) of the plugin, then add this between lines 51-52:
`
if ($(window).scrollTop() > this.fadeIn) {
	this.element.play();
	this.element.volume = 1;
}
`
